#server:
#  port: ${server_port:8088}
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-server:8761/eureka/
#
#spring:
#  application:
#    name: transaction-service

#spring:
#  application:
#    name: transaction-service
#  devtools:
#    remote:
#      secret: mysecret
#
#management:
#  security:
#    enabled: false
#
#kafka:
#  bootstrap-servers: localhost:9092
#  topic: test