#server:
#  port: ${server_port:8087}
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-server:8761/eureka/
#
#spring:
#  application:
#    name: customer-service
#kafka:
#  bootstrap-servers: localhost:9092
#  topic: test