#server:
#  port: ${server_port:9090}
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}
#
#spring:
#  application:
#    name: zuul-server
#
#management:
#  security:
#    enabled: false
#
#zuul:
#  routes:
#    bank-service:
#      path: /bank/**
#      url: http://localhost:8085/bank
#    branch-service:
#      path: /branch/**
#      url: http://localhost:8086/branch
#    customer-service:
#      path: /customer/**
#      url: http://localhost:8087/customer
#    transaction-service:
#      path: /transaction/**
#      url: http://localhost:8088/transaction
#    account-service:
#      path: /account/**
#      url: http://localhost:8089/account
#
